# Generated by Django 4.1.7 on 2023-04-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks_app', '0003_rename_task_attachments_task_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Goal',
            fields=[
                ('study_goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('details', models.TextField(blank=True)),
                ('manual_progress', models.BooleanField()),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Study_Goal_Attachment',
            fields=[
                ('attachments_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_goals_app.study_goal')),
            ],
        ),
        migrations.CreateModel(
            name='Related_Task',
            fields=[
                ('related_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_goals_app.study_goal')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_app.task')),
            ],
        ),
    ]
