# Generated by Django 4.1.7 on 2023-04-19 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_alter_course_name_alter_course_type_and_more'),
        ('study_goals_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_goal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.course'),
        ),
        migrations.AlterField(
            model_name='study_goal',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
