# Generated by Django 4.1.7 on 2023-04-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_alter_task_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_Attachments',
            new_name='Task_Attachment',
        ),
    ]
