# Generated by Django 4.1.7 on 2023-04-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.semester')),
            ],
        ),
    ]
